// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0JCSxBidpIVOqyYG5TbDiL2HQU5dERAs',
    appId: '1:151756368529:web:930636ffa131c041a52d30',
    messagingSenderId: '151756368529',
    projectId: 'pandsproject-70db1',
    authDomain: 'pandsproject-70db1.firebaseapp.com',
    storageBucket: 'pandsproject-70db1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDugo-yFM66kRf9fCERSXET6b5iQETkSJc',
    appId: '1:151756368529:android:03bd7da82069bd45a52d30',
    messagingSenderId: '151756368529',
    projectId: 'pandsproject-70db1',
    storageBucket: 'pandsproject-70db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUdrnO3FEEjN4kKLuITRdQX3B3lvbOx-8',
    appId: '1:151756368529:ios:f1d5d8c012eef4c7a52d30',
    messagingSenderId: '151756368529',
    projectId: 'pandsproject-70db1',
    storageBucket: 'pandsproject-70db1.firebasestorage.app',
    iosBundleId: 'com.example.p',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUdrnO3FEEjN4kKLuITRdQX3B3lvbOx-8',
    appId: '1:151756368529:ios:f1d5d8c012eef4c7a52d30',
    messagingSenderId: '151756368529',
    projectId: 'pandsproject-70db1',
    storageBucket: 'pandsproject-70db1.firebasestorage.app',
    iosBundleId: 'com.example.p',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0JCSxBidpIVOqyYG5TbDiL2HQU5dERAs',
    appId: '1:151756368529:web:dec7ca99bae4000aa52d30',
    messagingSenderId: '151756368529',
    projectId: 'pandsproject-70db1',
    authDomain: 'pandsproject-70db1.firebaseapp.com',
    storageBucket: 'pandsproject-70db1.firebasestorage.app',
  );
}
